version: "3.3"
services:
  web:
    build: .
    volumes:
      - .:/var/www/src
    environment:
      - SECRET_KEY = ${SECRET_KEY}
      - ENV = ${ENV}
      - DEBUG = ${DEBUG}
      - DOMAIN = ${DOMAIN}
      - ALIYUN_ACCESSKEY_ID = ${ALIYUN_ACCESSKEY_ID}
      - ALIYUN_ACCESSKEY_SECERT = ${ALIYUN_ACCESSKEY_SECERT}
      - ALIYUN_SAMPLE_SIGNNAME = ${ALIYUN_SAMPLE_SIGNNAME}
      - STATIC_ROOT = ${STATIC_ROOT}
  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/log
      - .:/var/www/src
    
    ports:
      - "0.0.0.0:80:80"
