version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:7704:6379"
  mysql:
    image: percona:5.7
    ports:
      - "127.0.0.1:7705:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build: .
    volumes:
      - .:/var/www/src
    links:
      - redis:cache1
      - mysql:db1
    command: "sh -c 'apt update && apt install -y vim make && cd /var/www/src/django_www && pip install appdirs && pip install importlib_metadata && poetry install && python manage.py migrate && python manage.py runserver'"
    environment:
      - DEPLOY=dev
      - REGION=all
      - DOMAIN=ludofire.ff.garena.all
      - LANGUAGE_CODE=en
      - TIME_ZONE=Etc/GMT+0
      - MANGO_API_URL=https://game.proxy.garenanow.com/mango
      - MANGO_TOKEN=EA7BEA15-B3BE-45DB-8FAC-35FA384E0A03
      - MANGO_EVENT_ID=graffiti
      - TRANSIFY_RESOURCES=565,740,726,2779
      - PROJECT_NAME=app
      - SENTRY_DSN=http://ff1095e99a80495aada4a1c7043a883f@sentry.web.garenanow.com/237
      - SENTRY_SAMPLE_RATE=1
      - STRESS_TEST=1
      - USE_NEW_TRANSIFY=1
      - USE_NEW_FFAPI=1
      - FFAPI_ACCESS_ID=ACG33JS0JN6U0M8QQVSS
      - FFAPI_ACCESS_SECRET=h5x1BYNpFJfY4Z0v2HGCgOV81WSZdnpY0hLl5FgLwlgjuYs5
      - FFAPI_SPACE_ID=sp-bfa436ff-16db-4611-841f-70ce43b57c9b
      - FFAPI_SERVICE_ID=sv-cd8695a9-bd4d-438b-84e0-d797457a2ad5
  nginx:
    image: nginx:alpine
    volumes: 
      - ./resty/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./resty/logs:/log
      - .:/var/www/src
    ports:
      - "127.0.0.1:7706:80"
