# Generated by Django 4.2.8 on 2023-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_remove_user_sc_ids_user_sc_nos_user_today_sc_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='today_sc_nos',
            field=models.CharField(blank=True, default='', help_text='今日答题no', max_length=1000),
        ),
    ]
