# Generated by Django 4.2.8 on 2023-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_remove_user_sc_nos_remove_user_vip_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='today_sc_nos',
            field=models.JSONField(default='{}', help_text='今日答题no'),
        ),
    ]
