# Generated by Django 4.2.8 on 2023-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.SmallIntegerField(choices=[(1, '1颗星'), (2, '2颗星'), (3, '3颗星')], default=1, help_text='难度系数')),
                ('no', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(max_length=255)),
                ('choice_d', models.CharField(max_length=255)),
                ('right_choice', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('description', models.TextField(default='')),
                ('status', models.SmallIntegerField(choices=[(1, '待上架'), (2, '上架'), (0, '下架')], default=1, help_text='题目的状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('right_counts', models.IntegerField(default=0, help_text='答对次数')),
                ('wrong_counts', models.IntegerField(default=0, help_text='答错次数')),
                ('collect_counts', models.IntegerField(default=0, help_text='被用户收藏次数')),
                ('tags', models.ManyToManyField(to='exercise.tag')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
    ]
