# Generated by Django 4.2.8 on 2023-12-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.SmallIntegerField(choices=[(1, '0颗星'), (2, '1颗星'), (3, '2颗星')], default=1, help_text='难度系数')),
                ('title', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(max_length=255)),
                ('choice_d', models.CharField(max_length=255)),
                ('right_choice', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('description', models.TextField(default='')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '待上架'), (2, '已上架')], default=1, help_text='题目的状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('right_counts', models.IntegerField(default=0, help_text='答对次数')),
                ('wrong_counts', models.IntegerField(default=0, help_text='答错次数')),
                ('collect_counts', models.IntegerField(default=0, help_text='被用户收藏次数')),
                ('tag', models.ForeignKey(default='Python基础', on_delete=django.db.models.deletion.SET_DEFAULT, to='exercise.tag')),
            ],
        ),
    ]
