# Generated by Django 4.2.8 on 2023-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='no',
            field=models.CharField(help_text='格式: <标签编号>-<题目唯一编号>', max_length=255),
        ),
    ]
