# Generated by Django 4.2.8 on 2023-12-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlechoice',
            name='tag',
        ),
        migrations.AddField(
            model_name='singlechoice',
            name='tags',
            field=models.ManyToManyField(to='exercise.tag'),
        ),
    ]
