# Generated by Django 4.2.8 on 2023-12-19 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_singlechoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
