# Generated by Django 4.2.8 on 2023-12-20 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_singlechoice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='choice_a',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choice_b',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choice_c',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choice_d',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
