# Generated by Django 4.2.8 on 2023-12-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_singlechoice_tags_singlechoice_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='no',
            field=models.CharField(help_text='题目唯一编号', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='exercise.tag'),
        ),
    ]
