# Generated by Django 4.2.8 on 2023-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_singlechoice_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='no',
            field=models.CharField(help_text='题目唯一编号', max_length=10, unique=True),
        ),
    ]
