# Generated by Django 4.2.8 on 2023-12-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_alter_singlechoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='no',
            field=models.CharField(help_text='题目唯一编号', max_length=15, unique=True),
        ),
    ]
